"""Add location column to user table

Revision ID: 80625f33f631
Revises: 9dcd32834365
Create Date: 2025-11-16 05:04:21.421634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80625f33f631'
down_revision: Union[str, Sequence[str], None] = '9dcd32834365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Qualification', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Qualification')
    # ### end Alembic commands ###
